name: docekrarm

on: workflow_dispatch

jobs:
  build-and-push:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      run: |
        docker buildx create --use
    - name: Set date
      id: date
      run: echo "::set-output name=date::$(date +'%m-%d-%Y')"
    - name: Build and Push image
      run: |
        ls build-docker-images/wazuh-dashboard && docker buildx build \
        --platform linux/arm64,linux/amd64 --tag ceron/wazuh-dashboard:${{ steps.date.outputs.date }} build-docker-images/wazuh-dashboard --build-arg WAZUH_VERSION=3.7 --build-arg WAZUH_TAG_REVISION=3.8.0 --build-arg WAZUH_UI_REVISION=1
